"""Synthetic SaaS ticket dataset with private grading labels."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal

from env.models import CustomerTier, Priority, SLAHours, TeamRoute

Category = Literal["billing", "engineering", "sales", "trust_safety", "ambiguous"]


@dataclass(frozen=True)
class TicketRecord:
    """Full ticket row (includes hidden labels for grading / reward)."""

    id: str
    text: str
    customer_tier: CustomerTier
    correct_route: TeamRoute
    correct_priority: Priority
    correct_sla: SLAHours
    category: Category
    acceptable_routes: tuple[TeamRoute, ...] = field(default_factory=tuple)
    priority_by_tier: dict[CustomerTier, Priority] | None = None
    sla_by_tier: dict[CustomerTier, SLAHours] | None = None
    urgency_score: float = 0.5

    def __post_init__(self) -> None:
        if not self.acceptable_routes:
            object.__setattr__(self, "acceptable_routes", (self.correct_route,))

    def gold_route(self) -> TeamRoute:
        return self.correct_route

    def gold_priority(self, tier: CustomerTier) -> Priority:
        if self.priority_by_tier is not None:
            return self.priority_by_tier[tier]
        return self.correct_priority

    def gold_sla(self, tier: CustomerTier) -> SLAHours:
        if self.sla_by_tier is not None:
            return self.sla_by_tier[tier]
        return self.correct_sla


def all_tickets() -> tuple[TicketRecord, ...]:
    return _TICKETS


# 38 tickets total — mixes billing, engineering, sales, trust & safety, ambiguous ops.
_TICKETS: tuple[TicketRecord, ...] = (
    TicketRecord(
        id="t_bil_001",
        text="Our Pro workspace was double-charged $499 on invoice INV-94821 for the same renewal period. Please refund the duplicate and send a corrected receipt.",
        customer_tier="pro",
        correct_route="billing",
        correct_priority="P2",
        correct_sla="4h",
        category="billing",
        urgency_score=0.45,
    ),
    TicketRecord(
        id="t_bil_002",
        text="I canceled last month but I was billed again this cycle. Account email is ops@contoso.io. Need statement credit and cancellation confirmation.",
        customer_tier="enterprise",
        correct_route="billing",
        correct_priority="P2",
        correct_sla="4h",
        category="billing",
        urgency_score=0.55,
    ),
    TicketRecord(
        id="t_bil_003",
        text="Tax ID on our invoices is outdated after incorporation. How do we update VAT details for the enterprise contract?",
        customer_tier="enterprise",
        correct_route="billing",
        correct_priority="P3",
        correct_sla="24h",
        category="billing",
        urgency_score=0.25,
    ),
    TicketRecord(
        id="t_bil_004",
        text="Free tier user here: I see an unexpected $1 verification charge on my card. Is that normal?",
        customer_tier="free",
        correct_route="billing",
        correct_priority="P4",
        correct_sla="72h",
        category="billing",
        urgency_score=0.2,
    ),
    TicketRecord(
        id="t_eng_001",
        text="GraphQL API returns 500 on the `createExportJob` mutation after yesterday's deploy. Repro steps attached. Production only.",
        customer_tier="enterprise",
        correct_route="engineering",
        correct_priority="P1",
        correct_sla="1h",
        category="engineering",
        urgency_score=0.95,
    ),
    TicketRecord(
        id="t_eng_002",
        text="Webhooks are delayed by 10–20 minutes since this morning. Signature verification still passes but SLAs are at risk.",
        customer_tier="pro",
        correct_route="engineering",
        correct_priority="P2",
        correct_sla="4h",
        category="engineering",
        urgency_score=0.7,
    ),
    TicketRecord(
        id="t_eng_003",
        text="CSV import fails with 'Row 4001: type mismatch' even though schema matches docs. Same file worked last week.",
        customer_tier="pro",
        correct_route="engineering",
        correct_priority="P3",
        correct_sla="24h",
        category="engineering",
        urgency_score=0.35,
    ),
    TicketRecord(
        id="t_eng_004",
        text="Mobile SDK crashes on startup on Android 14 when offline mode is enabled. Stack trace in attachment.",
        customer_tier="free",
        correct_route="engineering",
        correct_priority="P3",
        correct_sla="24h",
        category="engineering",
        urgency_score=0.4,
    ),
    TicketRecord(
        id="t_eng_005",
        text="Audit dashboard shows inconsistent totals between UTC and local timezone filters. Looks like a caching bug.",
        customer_tier="enterprise",
        correct_route="engineering",
        correct_priority="P2",
        correct_sla="4h",
        category="engineering",
        urgency_score=0.65,
    ),
    TicketRecord(
        id="t_sal_001",
        text="We're evaluating your enterprise plan for 800 seats. Need a security questionnaire completed and volume pricing.",
        customer_tier="enterprise",
        correct_route="sales",
        correct_priority="P2",
        correct_sla="4h",
        category="sales",
        urgency_score=0.5,
    ),
    TicketRecord(
        id="t_sal_002",
        text="Can we schedule a guided demo for next Tuesday for our purchasing committee?",
        customer_tier="pro",
        correct_route="sales",
        correct_priority="P3",
        correct_sla="24h",
        category="sales",
        urgency_score=0.3,
    ),
    TicketRecord(
        id="t_sal_003",
        text="Do you offer HIPAA BAA and a startup discount for companies under 50 employees?",
        customer_tier="free",
        correct_route="sales",
        correct_priority="P4",
        correct_sla="72h",
        category="sales",
        urgency_score=0.22,
    ),
    TicketRecord(
        id="t_sal_004",
        text="We're on Pro and want to understand SSO add-on pricing before renewal in 30 days.",
        customer_tier="pro",
        correct_route="sales",
        correct_priority="P3",
        correct_sla="24h",
        category="sales",
        urgency_score=0.28,
    ),
    TicketRecord(
        id="t_ts_001",
        text="A user is scraping our public project names and harassing maintainers via DMs with violent threats. Need urgent review and suspension.",
        customer_tier="pro",
        correct_route="trust_safety",
        correct_priority="P1",
        correct_sla="1h",
        category="trust_safety",
        urgency_score=0.98,
    ),
    TicketRecord(
        id="t_ts_002",
        text="Report: coordinated spam accounts posting malware links in comment threads. Example links attached.",
        customer_tier="enterprise",
        correct_route="trust_safety",
        correct_priority="P1",
        correct_sla="1h",
        category="trust_safety",
        urgency_score=0.92,
    ),
    TicketRecord(
        id="t_ts_003",
        text="Someone is impersonating our brand with a fake login page cloned from your hosted UI. Trademark issue.",
        customer_tier="enterprise",
        correct_route="trust_safety",
        correct_priority="P2",
        correct_sla="4h",
        category="trust_safety",
        urgency_score=0.88,
    ),
    TicketRecord(
        id="t_ts_004",
        text="User posting private customer PII in a public ticket including credit card fragments. Please remove and advise on disclosure.",
        customer_tier="free",
        correct_route="trust_safety",
        correct_priority="P1",
        correct_sla="1h",
        category="trust_safety",
        urgency_score=0.9,
    ),
    TicketRecord(
        id="t_amb_001",
        text="Our SSO SAML login fails intermittently for ~10% of enterprise users. IdP metadata unchanged. Might be config or a product bug—please advise.",
        customer_tier="enterprise",
        correct_route="engineering",
        correct_priority="P2",
        correct_sla="4h",
        category="ambiguous",
        acceptable_routes=("engineering", "sales"),
        priority_by_tier={"enterprise": "P2", "pro": "P3", "free": "P4"},
        sla_by_tier={"enterprise": "4h", "pro": "24h", "free": "72h"},
        urgency_score=0.72,
    ),
    TicketRecord(
        id="t_amb_002",
        text="We're blocked on procurement because the compliance PDF on your pricing page contradicts the enterprise agreement draft our rep sent.",
        customer_tier="enterprise",
        correct_route="sales",
        correct_priority="P2",
        correct_sla="4h",
        category="ambiguous",
        acceptable_routes=("sales", "billing"),
        priority_by_tier={"enterprise": "P2", "pro": "P3", "free": "P4"},
        sla_by_tier={"enterprise": "4h", "pro": "24h", "free": "72h"},
        urgency_score=0.6,
    ),
    TicketRecord(
        id="t_amb_003",
        text="Refund was promised but credit never arrived; meanwhile our admin console shows 'subscription active' and engineers say API keys still work.",
        customer_tier="pro",
        correct_route="billing",
        correct_priority="P3",
        correct_sla="24h",
        category="ambiguous",
        acceptable_routes=("billing", "engineering"),
        urgency_score=0.58,
    ),
    TicketRecord(
        id="t_amb_004",
        text="New hire cannot access the shared workspace; SSO groups sync but seat assignment UI errors. Need this fixed before board meeting tomorrow.",
        customer_tier="enterprise",
        correct_route="engineering",
        correct_priority="P2",
        correct_sla="4h",
        category="ambiguous",
        acceptable_routes=("engineering", "sales"),
        priority_by_tier={"enterprise": "P2", "pro": "P3", "free": "P4"},
        sla_by_tier={"enterprise": "4h", "pro": "24h", "free": "72h"},
        urgency_score=0.68,
    ),
    TicketRecord(
        id="t_amb_005",
        text="We want to expand seats mid-cycle and need both a quote and confirmation that the new proration math matches what the billing portal shows.",
        customer_tier="pro",
        correct_route="sales",
        correct_priority="P3",
        correct_sla="24h",
        category="ambiguous",
        acceptable_routes=("sales", "billing"),
        urgency_score=0.42,
    ),
    TicketRecord(
        id="t_amb_006",
        text="Toxic thread in our customer community with slurs; also the report button returns 403—unclear if moderation or bug.",
        customer_tier="pro",
        correct_route="trust_safety",
        correct_priority="P1",
        correct_sla="1h",
        category="ambiguous",
        acceptable_routes=("trust_safety", "engineering"),
        urgency_score=0.85,
    ),
    TicketRecord(
        id="t_amb_007",
        text="Invoice PDF totals do not match usage export CSV for last month—finance needs help reconciling before audit.",
        customer_tier="enterprise",
        correct_route="billing",
        correct_priority="P2",
        correct_sla="4h",
        category="ambiguous",
        acceptable_routes=("billing", "engineering"),
        urgency_score=0.52,
    ),
    TicketRecord(
        id="t_amb_008",
        text="Interested in upgrading from Pro; also seeing random small metered charges we cannot map to documented rates.",
        customer_tier="pro",
        correct_route="sales",
        correct_priority="P3",
        correct_sla="24h",
        category="ambiguous",
        acceptable_routes=("sales", "billing"),
        urgency_score=0.48,
    ),
    TicketRecord(
        id="t_cap_001",
        text="Regional outage: EU data plane read latency >2s, error budget burned. Status page not updated.",
        customer_tier="enterprise",
        correct_route="engineering",
        correct_priority="P1",
        correct_sla="1h",
        category="engineering",
        urgency_score=0.97,
    ),
    TicketRecord(
        id="t_cap_002",
        text="Finance cannot close quarter: usage metering stalled for 4 hours; execs want assurance numbers in billing DB are intact.",
        customer_tier="enterprise",
        correct_route="engineering",
        correct_priority="P1",
        correct_sla="1h",
        category="ambiguous",
        acceptable_routes=("engineering", "billing"),
        urgency_score=0.9,
    ),
    TicketRecord(
        id="t_cap_003",
        text="Moderation queue backlog is 48h; reporters claim child safety content is still live. Need immediate triage.",
        customer_tier="enterprise",
        correct_route="trust_safety",
        correct_priority="P1",
        correct_sla="1h",
        category="trust_safety",
        urgency_score=0.99,
    ),
    TicketRecord(
        id="t_cap_004",
        text="Prospect pilot ends Friday; legal needs MSA redlines AND a fix for broken sandbox signup blocking technical eval.",
        customer_tier="enterprise",
        correct_route="sales",
        correct_priority="P2",
        correct_sla="4h",
        category="ambiguous",
        acceptable_routes=("sales", "engineering"),
        priority_by_tier={"enterprise": "P2", "pro": "P3", "free": "P4"},
        sla_by_tier={"enterprise": "4h", "pro": "24h", "free": "72h"},
        urgency_score=0.75,
    ),
    TicketRecord(
        id="t_cap_005",
        text="Automated fraud alerts firing: many failed card retries across tenants; could be gateway or billing rule change.",
        customer_tier="pro",
        correct_route="billing",
        correct_priority="P2",
        correct_sla="4h",
        category="ambiguous",
        acceptable_routes=("billing", "engineering"),
        urgency_score=0.78,
    ),
    TicketRecord(
        id="t_cap_006",
        text="Developer blog comments flooded with phishing; engineering worries WAF bypass. Trust team must remove content.",
        customer_tier="free",
        correct_route="trust_safety",
        correct_priority="P2",
        correct_sla="4h",
        category="ambiguous",
        acceptable_routes=("trust_safety", "engineering"),
        urgency_score=0.8,
    ),
    TicketRecord(
        id="t_cap_007",
        text="Seat limit discrepancies between sales order form and in-app license count; customer threatening churn before renewal.",
        customer_tier="enterprise",
        correct_route="billing",
        correct_priority="P2",
        correct_sla="4h",
        category="ambiguous",
        acceptable_routes=("billing", "sales"),
        urgency_score=0.62,
    ),
    TicketRecord(
        id="t_cap_008",
        text="Lightweight question: dark mode toggle missing in settings—but only for one experimental build channel.",
        customer_tier="free",
        correct_route="engineering",
        correct_priority="P4",
        correct_sla="72h",
        category="engineering",
        urgency_score=0.15,
    ),
    TicketRecord(
        id="t_cap_009",
        text="Renewal discount promised in Zoom call last week not reflected in checkout; AE is on PTO; need billing correction today.",
        customer_tier="enterprise",
        correct_route="billing",
        correct_priority="P2",
        correct_sla="4h",
        category="ambiguous",
        acceptable_routes=("billing", "sales"),
        urgency_score=0.64,
    ),
    TicketRecord(
        id="t_cap_010",
        text="Export job contains other tenant's row fragments—possible isolation bug. Customer CCed legal.",
        customer_tier="enterprise",
        correct_route="engineering",
        correct_priority="P1",
        correct_sla="1h",
        category="engineering",
        acceptable_routes=("engineering", "trust_safety"),
        urgency_score=0.96,
    ),
    TicketRecord(
        id="t_bil_005",
        text="ACH pull succeeded twice on the same renewal date; bank shows two debits for INV-22001.",
        customer_tier="pro",
        correct_route="billing",
        correct_priority="P2",
        correct_sla="4h",
        category="billing",
        urgency_score=0.5,
    ),
    TicketRecord(
        id="t_eng_006",
        text="Feature flag rollout appears stuck at 42% canary; some regions never receive the new config.",
        customer_tier="enterprise",
        correct_route="engineering",
        correct_priority="P2",
        correct_sla="4h",
        category="engineering",
        urgency_score=0.58,
    ),
    TicketRecord(
        id="t_sal_005",
        text="Nonprofit discount: need written quote for 120 seats and onboarding timeline for Q3.",
        customer_tier="pro",
        correct_route="sales",
        correct_priority="P3",
        correct_sla="24h",
        category="sales",
        urgency_score=0.26,
    ),
    TicketRecord(
        id="t_ts_005",
        text="Doxxing in comments: full home address posted. Please remove and enforce policy.",
        customer_tier="free",
        correct_route="trust_safety",
        correct_priority="P1",
        correct_sla="1h",
        category="trust_safety",
        urgency_score=0.94,
    ),
    TicketRecord(
        id="t_amb_009",
        text="Partner portal billing address locked read-only after migration; Sales says AE can fix but UI errors on save.",
        customer_tier="enterprise",
        correct_route="sales",
        correct_priority="P2",
        correct_sla="4h",
        category="ambiguous",
        acceptable_routes=("sales", "engineering"),
        priority_by_tier={"enterprise": "P2", "pro": "P3", "free": "P4"},
        sla_by_tier={"enterprise": "4h", "pro": "24h", "free": "72h"},
        urgency_score=0.56,
    ),
)
